### PR TITLE
Create hub and spoke component

### PR DESCRIPTION
**Pull request by johnhwhite**
[design](https://blackbaud.invisionapp.com/console/share/AQ2I2DLEUR)

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component](https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component](https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component](https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component](https://developer.blackbaud.com/skyux-pages?_sp.spa=pr-hub-and-spoke-component)

**Review by Blackbaud-PaulCrowder — APPROVED** [review]

**Pull request merged**
